<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Article' => 'Заголовок',
    'Author' => 'Автор',
    'Created At' => 'Создан',
    'Updated At' => 'Обновлён',
    'Description' => 'Описание',
    'Image' => 'Картинка',
    'Intro Text' => 'Краткое описание',
    'Verification Code' => 'Код подтверждения',
    'My Company' => 'Моя Компания',
    'Login' => 'Войти',
    'News' => 'Новости',
    'Home' => 'Главная',
    'Russian' => 'Русский',
    'Update' => 'Обновить',
    'Delete' => 'Удалить',
    'Create News' => 'Создать Новость',
    'About' => 'О Нас',
    'Contact' => 'Контакты',
    'Signup' => 'Зарегестрироватся',
    'Submit' => 'Подтвердить',
    'verifyCode' => 'Код подтверждения',
    'Body' => 'Текст',
    'Subject' => 'Тема',
    'Email' => 'Емейл',
    'Name' => 'Имя',
    'Username' => 'Имя Пользователя',
    'Password' => 'Пароль',
    'RememberMe' => 'Запомнить меня',
    'Reset password' => 'Сбросить пароль',
    'Save' => 'Сохранить',
    'Request password reset' => 'Запрос на сброс пароля',
    'Send' => 'Отправить',
    'reset it' => 'Сбросить',
    'Logout' => 'Выйти',
    'If you forgot your password you can' => 'Если вы забыли пароль, вы можете',
];
